services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=myPasss123docker
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  
  vault:
    image: hashicorp/vault:1.13.0
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    depends_on:
      - sqlserver